### ISSUE TITLE
A model graph plot problem.

### ISSUE THREAD

**Issue by lk1983823** [pnnl/neuromancer#1]
Thanks for the great work on such a flexible model based RL framwork. 
Recently, I try to change the default  input settings in `dynamics.py` from `DEFAULT_INPUT_KEYS=["x0", "Yf"]` to `DEFAULT_INPUT_KEYS=["x0", "Yp"]` and `nsteps = data[self.input_key_map['Yp']].shape[1]` in the "forward" method, and run `example/system_identification/two_tank_neural_ssm.py`   successfully. However, after plotting the model graph, I find the connection `Yf` from `dataset` to `Y_pred_dynamics_eq_Yf` disappears, like below. They are  the inputs to calculate the mse loss.

![two_tank_neural_ssm_2](https://user-images.githubusercontent.com/20237650/202889958-2018c24a-317c-4281-a068-958d4d663a2b.png)

Is there anyone can help to find out the problem and fix this? Thanks!

**Comment by drgona** [comment]
Thank you for raising the issue @lk1983823.

Indeed you can change the default input key to the dynamics class from 'Yf' to 'Yp' as these would be used only to infer the length of the prediction horizon in the n-step ahead rollout. In fact, any string could be used for this purpose as key pointing to the 3D tensor with the second dimension defining the time horizon.

As for the problem graph you showed, it seems correct. 'Yp' is not used as input in the constraint Y_pred_dynamics_eq_Yf.
This constraint is defined based on two variables with names f"Y_pred_{dynamics_model.name}" and 'Yf' and as follows:
https://github.com/pnnl/neuromancer/blob/master/examples/system_identification/two_tank_neural_ssm.py#L224

**Comment by lk1983823** [comment]
> 

Sorry about my poor drawing :(.  The green mark on the right above the figure is Yf. I don't know why the connection Yf from dataset to Y_pred_dynamics_eq_Yf disappears. 
![two_tank_neural_ssm_2](https://user-images.githubusercontent.com/20237650/205227387-562ba072-3fe8-4cb6-81d5-aa3a633960ca.png)

**Comment by drgona** [comment]
Hi @lk1983823, this issue should be resolved in the latest update. There have been some inconsistencies with variable names during the plotting of the computational graph.
