### ISSUE TITLE
Constraint weights saved as nan if set to 0.0

### ISSUE THREAD

**Issue by sovasisht** [pnnl/neuromancer#10]
During the training process, if any of the constraint weights, Q_con_x, Q_dx, Q_fd, etc, are set to 0.0, the logger saves them as NaN values. When the trained model is reloaded to run further evaluation experiments, these NaN values end up producing NaN trajectories.

Current workaround: Use if statement to explicitly set these NaN parameters to 0.0 before running further training or testing.

**Comment by aarontuor** [comment]
Can you provide an example?

**Comment by aarontuor** [comment]
This issue has been resolved. There was an error in the logging that is now fixed.
