### ISSUE TITLE
pip install vs conda install pytorch versioning

### ISSUE THREAD

**Issue by johnviljoen** [pnnl/neuromancer#111]
When installing using the PIP technique, PyTorch 2.0.1 is used, whereas both the osxarm64, and linux yaml conda installs use PyTorch < 2.0. 

This is problematic for me because I use functorch, which is part of PyTorch from 2.x onwards, and is only available as a pip install for PyTorch < 2.0, which then interferes with the conda install of PyTorch as it will uninstall the conda pytorch, and reinstall a pip PyTorch, breaking cuda acceleration in the process. 

This issue is then to ask the conda PyTorch installs to support the same version as the pip install.

**Comment by RBirmiwal** [comment]
Can you try using this updated linux_env.yml, attached here. (I cannot attach .yml files to GitHub so please replace .txt extension with .yml). Then run the conda install instructions as on the main readme. I was running into issues with the previous linux_env.yml as well. The PyTorch version here has been bumped to 2.0.1. I don't have a windows nor use functorch, so I cannot confirm that it works though. 

Alternatively, neuromancer can now be installed directly from PyPI: 'pip install neuromancer' (on an virtual environment with Python 3.9 installed). Again don't have windows so can't confirm that will work for you, but that works on my Mac. 

[linux_env_fixed.txt](https://github.com/pnnl/neuromancer/files/13221240/linux_env_fixed.txt)
