### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by MoReZavvar** [pnnl/neuromancer#113]
Hi,

I installed the Neuromancer by creating a conda with python 3.10.4. environment and pip install using Pycharm and when running pytest on the tests, they all pass. About the error: It is related to the plot (pltCL) step of the given examples in GitHub, as a reference I took Example 3 in the control section but I received very similar errors for every example. Please find attached to this mail screenshots of the error message: 

pltCL(Y=trajectories['x'].detach().reshape(nsteps + 1, nx),
ValueError: only one element tensors can be converted to Python scalars

![screen](https://github.com/pnnl/neuromancer/assets/121087030/e71d6887-4988-4e5b-8860-00ea3b29c40c)

Thank you very much in advance for considering this issue!

**Comment by RBirmiwal** [comment]
@MoReZavvar sorry it has taken a while to get back to you. This was a tricky error. Can you please retry with specifically Python version 3.10.12? 

You can also now use pip install for neuromancer: "pip install neuromancer". 

Thank you
