### ISSUE TITLE
Koopman Operators imports

### ISSUE THREAD

**Issue by evelynmitchell** [pnnl/neuromancer#116]
In Part_8_nonauto_DeepKoopman.ipynb the initial install cell for colab should be:
```
!pip install fastapi kaleido python-multipart uvicorn
!pip install lida
!pip install "neuromancer[examples] @ git+https://github.com/pnnl/neuromancer.git@master"
```
to resolve an import error for lida:
```
"""ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
```

**Comment by RBirmiwal** [comment]
@evelynmitchell I see. I am able to reproduce this error, though I am still able to proceed and run the entire notebook correctly. Are you still able to run this notebook? 

The dependency issue is being looked into in the meanwhile. 

Thanks

**Comment by evelynmitchell** [comment]
I can run the notebook with the correction I submitted.

**Comment by RBirmiwal** [comment]
You should still be able to run the notebook without any correction. I just ran the notebook. The "error" raised seems to be an issue with Colab. The lida package is not directly used by NeuroMANCER. We are taking a look into it. Thanks!
