### ISSUE TITLE
Inconsistency naming of constraint module

### ISSUE THREAD

**Issue by clegaard** [pnnl/neuromancer#13]
Some of the example uses the constraint module like

``` Python
import neuromancer as nm

# declare constraints 
x = nm.constraints.variable("x")[:, [0]]
```

Unless anaconda does something magical, I suspect this should be `nm.constraint` to match the name of the file.

**Comment by aarontuor** [comment]
This appears to be fixed in the latest release. I will close this issue. Please open an issue with file and line number mentioned if the problem persists.
