### ISSUE TITLE
Forward method of Node with multiple outputs not mapping the output when MLP is the operator

### ISSUE THREAD

**Issue by brunopjacob** [pnnl/neuromancer#139]
Hi y'all! I noticed that when we have an instance of a `Node` with multiple outputs and operating with a `blocks.MLP`, the mapping to the output variables doesn't follow the same behavior as when the operator is a function.
 
I tried to illustrate the issue in the snippet below: I create a block, a function and some data. Then, I create two nodes: one to illustrate the forward pass of the block, and the other to do the same with the function. Notice the multiple outputs in the node definitions.

``` 
import torch
import torch.nn as nn
from neuromancer.modules import blocks
from neuromancer.system import Node

test_block = blocks.MLP(insize=2, outsize=3,
                  bias=True,
                  nonlin=torch.nn.Tanh,
                  hsizes=[20] * 4)

def test_fun(x1,x2):
    return x1+x2, x1-x2, x1*x2

data = {'x1': torch.rand(10, 1), 'x2': torch.rand(10, 1)}

node_1 = Node(test_fun, ['x1','x2'], ['vx','vy','p'])
print(node_1(data).keys())
print(node_1(data)["vx"].shape)

node_2 = Node(test_block, ['x1','x2'], ['vx','vy','p'])
print(node_2(data).keys())
print(node_2(data)["vx"].shape)
``` 

The result from `node_2` has shape `[10,3]`, which shouldn't be the case; it seems to me that the issue is here: https://github.com/pnnl/neuromancer/blob/e0f02e592ce32584a03fba52d422aad4bbb4276d/src/neuromancer/system.py#L50-L52
 
I think an easy solution for that is to do a `.split` on the output tensor after the forward method is called, after checking that the result is not a tuple (since that for the tuple case, i.e., function case, things work just fine).

```
output = self.callable(*inputs) 
if not isinstance(output, tuple):
   output = output.split(1, dim=1)
```

I did some tests and I guess that way the mapping would work 😸 

Thanks!

**Comment by drgona** [comment]
Thanks @brunopjacob 
I would keep the API as is, .split could create lot of issues.
We could create a warning for the user when instantiating Node class with different number of symbolic outputs than the length of the tuple output of the wrapped callable.
