### ISSUE TITLE
TypeError with numpy.ndarray in Function Expressions

### ISSUE THREAD

**Issue by LucasBoTang** [pnnl/neuromancer#140]
### Description

When using the `neuromancer` library for function expression with Python's built-in list, everything works as expected. However, when using a `numpy` array for the function expression, the type of the resulting expression becomes `numpy.ndarray` instead of `neuromancer.constraint.Variable`, which prevents further operations such as `minimize()` from being used.

### Code to Reproduce

```Python
import neuromancer as nm
import numpy as np

x = nm.constraint.variable("x")

# expression with list
c = [[0.0200],
     [0.0300]]
f = sum(c[i] * x[:, i] for i in range(2))
print(type(f))
f.minimize(weight=1.0, name="obj")

# expression with numpy array
c = np.array(c)
f = sum(c[i] * x[:, i] for i in range(2))
print(type(f))
f.minimize(weight=1.0, name="obj")
```

#### Expected Behavior

The type of `f` should be `neuromancer.constraint.Variable` in both cases, allowing the use of `minimize()` method.

#### Actual Behavior

The type of `f` when using `numpy` arrays is `numpy.ndarray`, leading to an **AttributeError** when calling `f.minimize(weight=1.0, name="obj")`:

```
<class 'neuromancer.constraint.Variable'>
<class 'numpy.ndarray'>
Traceback (most recent call last):
  File "path\to\file.py", line 18, in <module>
    f.minimize(weight=1.0, name="obj")
AttributeError: 'numpy.ndarray' object has no attribute 'minimize'
```

### Environment

- Python version: [3.10.13]
- Neuromancer version: [1.4.2] (Develop Branch)
- Numpy version: [1.26.3]

**Comment by LucasBoTang** [comment]
This issue seems to be caused by recent changes in `numpy` that override the Python `sum` builtin, affecting the expected behavior when `numpy` arrays are used in function expressions.

**Comment by drgona** [comment]
we have to use torch.tensor instead of np.array in this case
