### ISSUE TITLE
Documentation not accessible at https://pnnl.github.io/neuromancer/

### ISSUE THREAD

**Issue by joshuaeh** [pnnl/neuromancer#141]
I get a 404 error when I navigate to https://pnnl.github.io/neuromancer/.

It might be that the documentation is still under construction, I'd suggest noting that in the README if that's the case.

Apologies if the issue is known or a nuisance. I took a look at closed issues and didn't see anything.

JH

**Comment by RBirmiwal** [comment]
Hi @joshuaeh . 

Apologies for the 404 error. The site is now fixed and up and running at https://pnnl.github.io/neuromancer/. Please let me know if you have any questions or need any further assistance. Thank you.
