### ISSUE TITLE
Suggesting to add the source code of the paper to the examples

### ISSUE THREAD

**Issue by XinyuanLiao** [pnnl/neuromancer#15]
Hi! developer:
I suggest that the source code of the paper using the framework can be added to the examples, such as the source code of the article physics-constrained deep learning of multi-zone building thermal dynamics. It's really difficult to understand the framework from scratch.

**Comment by XinyuanLiao** [comment]
Hi! developer:
I suggest that the source code of the paper using the framework can be added to the examples, such as the source code of the article physics-constrained deep learning of multi-zone building thermal dynamics. It's really difficult to understand the framework from scratch.

**Comment by drgona** [comment]
Hi, @XinyuanLiao thank you for the inquiry! 

The code associated with the paper "physics-constrained deep learning of multi-zone building thermal dynamics" is available in this branch:
https://github.com/pnnl/neuromancer/tree/system_ID_building
Please see the readme for the instructions on where to find the training and evaluation code.
However, this implementation is a legacy code that is not backward compatible with the current version of Neuromancer. It can still provide you with all the necessary implementation details used in the paper.

We will keep expanding the generic library of our examples to facilitate the adoption of the methods. If you have requests for specific applications or features to be displayed in the example please let us know. Also, we welcome community contributions by integrating external examples into the core library. You can find more in our community guidelines.
https://github.com/pnnl/neuromancer#contributing-examples

**Comment by XinyuanLiao** [comment]
Thank you for your reply. I will check it carefully.
