### ISSUE TITLE
How to write custom ODEs?

### ISSUE THREAD

**Issue by aleksejs-fomins** [pnnl/neuromancer#153]
Dear Neuromancer developers.

I am new to Neuromancer, and I am interested in using it for modeling custom ODEs, as well as doing parameter inference on custom ODEs. Would you be so kind to point me to the documentation or an example that describes how this can be done. I have looked at a few example notebooks on the website, but they seem to use model systems like `psl.systems['Brusselator1D']`, as opposed to custom ODEs. Perhaps I did not look long enough, I am sorry.

Cheers,
Aleksejs

**Comment by drgona** [comment]
Hi @aleksejs-fomins 

I recommend you have a look at our existing examples on modeling ODEs. 
Specifically, you can check these two examples that implement custom ODEs.
Part_2_param_estim_ODE.ipynb
https://colab.research.google.com/github/pnnl/neuromancer/blob/master/examples/ODEs/Part_2_param_estim_ODE.ipynb#scrollTo=c41df1bd&line=1&uniqifier=1
Part_3_UDE.ipynb
https://colab.research.google.com/github/pnnl/neuromancer/blob/master/examples/ODEs/Part_3_UDE.ipynb#scrollTo=c41df1bd&line=1&uniqifier=1

If you are interested in doing control with ODEs you can check:
https://colab.research.google.com/github/pnnl/neuromancer/blob/master/examples/control/Part_3_ref_tracking_ODE.ipynb

For future functionality questions, please use the discussion forum instead. Issues should only be used to report bugs.
https://github.com/pnnl/neuromancer/discussions
