### ISSUE TITLE
Neuromancer Runtime Error +PINNs

### ISSUE THREAD

**Issue by AnmarAl-Adly** [pnnl/neuromancer#154]
I'm currently using the Neuromancer library to build a PINN for a project involving dynamic load simulation in structural engineering models. 
When I tried to integrate a specific term into the PINN formulation, I received a RuntimeError related to tensor differentiation (attached screen photo). 

**### RuntimeError: One of the differentiated Tensors does not appear to have been used in the graph. If you want this behaviour, set allow_unused to True.** 

Interestingly, when I remove the` - (p * delta)` term, the error disappears, and the model runs as expected with no runtime issues. 

Could you please explain why this error is occurring and suggest any possible solutions or workarounds?

Code snippet:
```
# get the symbolic derivatives
dy_dt = y_hat.grad(t)
d2y_d2t=dy_dt.grad(x)
dy_dx = y_hat.grad(x)
d2y_d2x=dy_dx.grad(x)
d3y_d3x=d2y_d2x.grad(x)
d4y_d4x=d3y_d3x.grad(x)

# Constants and model parameters should be defined or imported
EI = torch.tensor(EI, dtype=torch.float32)  # Ensure EI is a tensor
m = torch.tensor(m, dtype=torch.float32)    # Mass per unit length
p = torch.tensor(p, dtype=torch.float32)    # Load magnitude
vs = torch.tensor(vs, dtype=torch.float32)  # Speed 

# Calculate load position and delta for moving load
load_position = x - vs * t
delta = torch.exp(-((load_position / 0.1) ** 2)) / (0.1 * torch.sqrt(torch.tensor(torch.pi)))

# Physics-informed Neural Network equation
f_pinn = (EI * d4y_d4x + m * d2y_d2t - (p * delta))*dy_dx/dy_dx
```
 
```
# check the shapes of the forward pass of the symbolic PINN terms
print(dy_dt({**net_out, **train_data.datadict}).shape)
print(d2y_d2t({**net_out, **train_data.datadict}).shape)
print(dy_dx({**net_out, **train_data.datadict}).shape)
print(d2y_d2x({**net_out, **train_data.datadict}).shape)
print(d3y_d3x({**net_out, **train_data.datadict}).shape)
print(d4y_d4x({**net_out, **train_data.datadict}).shape)
print(f_pinn({**net_out, **train_data.datadict}).shape)
```

Output: 
--------
torch.Size([1200, 1])
torch.Size([1200, 1])
torch.Size([1200, 1])
torch.Size([1200, 1])
torch.Size([1200, 1])
torch.Size([1200, 1])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-23-364a458d6f00>](https://localhost:8080/#) in <cell line: 8>()
      6 print(d3y_d3x({**net_out, **train_data.datadict}).shape)
      7 print(d4y_d4x({**net_out, **train_data.datadict}).shape)
----> 8 print(f_pinn({**net_out, **train_data.datadict}).shape)

6 frames
[/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py](https://localhost:8080/#) in _engine_run_backward(t_outputs, *args, **kwargs)
    742         unregister_hooks = _register_logging_hooks_on_whole_graph(t_outputs)
    743     try:
--> 744         return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    745             t_outputs, *args, **kwargs
    746         )  # Calls into the C++ engine to run the backward pass

RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

![image](https://github.com/pnnl/neuromancer/assets/101713749/686544fd-edba-4a6f-9d43-503a018e8861)
![image](https://github.com/pnnl/neuromancer/assets/101713749/ecf67a6e-8ed0-4743-b9d1-97c30b3bd4e6)

**Comment by drgona** [comment]
Hi @AnmarAl-Adly, can you please provide a complete code example to recreate the error?

**Comment by drgona** [comment]
You have a typo in defining symbolic derivative in this cell: https://colab.research.google.com/drive/1RbIVP8EgGRs96LI8iwrG4ZH95d2CM4Du#scrollTo=SsnFxw-r5ir-&line=1&uniqifier=1

`d2y_d2t=dy_dt.grad(x) ` should be `d2y_d2t=dy_dt.grad(t)`

after this the code runs

**Comment by AnmarAl-Adly** [comment]
ohh! my bad!!
Thank you.
