### ISSUE TITLE
Initial and boundary conditions with derivatives +PINNs

### ISSUE THREAD

**Issue by AnmarAl-Adly** [pnnl/neuromancer#155]
Hi @drgona,

I've updated the PINN code for for a project involving dynamic load simulation in structural engineering models and tried to incorporate the initial and boundary conditions required for a simply supported beam. The conditions are defined as follows:

Boundary conditions: 1- Deflection of beam y= 0 at x=0 and x =L (Which I did it in the code)
2-The second derivative of deflection with respect to position,
𝑑2𝑦_𝑑2 = 0 (x =0 and x =L) (I'm stuck here!)

Initial condition: 1- Deflection (y) = 0 (t =0 ) (I did it )
2- dy_dt = 0 at (t =0) (I'm stuck here!)
Please see the attached example code link.
https://colab.research.google.com/drive/1Q4aCWcDxh1IRVT1QltjSbwG5fNDTK9yL?usp=sharing

Could you please provide some guidance on this?

With regards,
Anmar

**Comment by drgona** [comment]
For future requests about problem formulations please use our Discussions portal: https://github.com/pnnl/neuromancer/discussions
