### ISSUE TITLE
Can it run on GPU?

### ISSUE THREAD

**Issue by l2late** [pnnl/neuromancer#16]
Hello, I have been trying the module out over the past few days, but I haven't been able to run in on GPU, even after installing the CUDA enabled version of PyTorch. 
Is the module supposed to run on CPU only or have I misconfigured something in my environment?
 
Thank you :)

**Comment by l2late** [comment]
I fixed it by removing all cuda and pytorch related modules in the .yml file and install pytorch with pip while the conda environment was activated.

**Comment by gy2256** [comment]
Do you need to modify the Neuromancer source code to include to(device) to enable GPU based training?
