### ISSUE TITLE
Can't reproduce results in branch building_ctrl

### ISSUE THREAD

**Issue by Qiuzhuang** [pnnl/neuromancer#17]
It seems that I can not be able to reproduce the paper's results with this branch? 
1. which psl/slim version that this branch depends on?
2. it seem that Y out's max is 40 while in paper it seems that it is 32, here is the debug screen shot:
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/334695/223727091-6d1ecaf8-2f1a-4a87-9a45-d501230dc20f.png">

Can you please give some guidances to see if we can reproduce the results from paper `Deep Learning Explicit Di erentiable Predictive Control Laws for Buildings`?

Many thanks.

**Comment by drgona** [comment]
Hi @Qiuzhuang, the building_ctrl branch is not actively maintained. 
Both psl and slim packages are way ahead of the versions used in this branch.

If you want to make the building_ctrl branch work, you might want to use the submodule version in the DPC branch.
https://github.com/pnnl/neuromancer/tree/DPC
However, it comes with no guarantees of compatibility.

The best approach I would recommend would be to reproduce the results in the latest master branch by getting inspired by the building_ctrl branch. Hope that helps.

All the best,
Jan
