### ISSUE TITLE
PINN example Part 4: Laplace's Equation (steady-state) - error in final plots

### ISSUE THREAD

**Issue by drgona** [pnnl/neuromancer#178]
There is a type error in the final plot cell.

https://colab.research.google.com/github/pnnl/neuromancer/blob/master/examples/PDEs/Part_4_PINN_LaplaceEquationSteadyState.ipynb#scrollTo=8Kxm5XLfSUUp&line=7&uniqifier=1

`TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

**Comment by brunopjacob** [comment]
Fixed in https://github.com/pnnl/neuromancer/pull/191.
