### ISSUE TITLE
PINN example Part 6: Navier-Stokes equation (lid-driven cavity flow, steady-state, KAN) - device error

### ISSUE THREAD

**Issue by drgona** [pnnl/neuromancer#179]
there is an error at the beginning of the notebook when forward passing the model with instantiated dataset 

https://colab.research.google.com/github/pnnl/neuromancer/blob/master/examples/PDEs/Part_6_PINN_NavierStokesCavitySteady_KAN.ipynb#scrollTo=NEAMxh6ASU4D&line=1&uniqifier=1

`pde_net(train_data.datadict)`

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
`

**Comment by brunopjacob** [comment]
Fixed in https://github.com/pnnl/neuromancer/pull/191.
