### ISSUE TITLE
Two_tank_node

### ISSUE THREAD

**Issue by ghimirepallavi** [pnnl/neuromancer#18]
I tried to run the example but I always receive the attached error. I have windows 11 , Conda version:  conda 23.3.1 

![error](https://user-images.githubusercontent.com/130812282/232241990-fe532b8e-7325-43e6-bc43-451b68510a25.png)

**Comment by drgona** [comment]
Hi @ghimirepallavi can you please provide high res screenshot or copy-paste the error in the message?
