### ISSUE TITLE
some redundancies in the code

### ISSUE THREAD

**Issue by drgona** [pnnl/neuromancer#181]
I noticed some redundancies in our codebase. No biggie but we should cleanup in the next release.

Specifically scaling and clamping helper functions are implemented twice 
here:
https://github.com/pnnl/neuromancer/blob/master/src/neuromancer/modules/blocks.py#L179
and here:
https://github.com/pnnl/neuromancer/blob/master/src/neuromancer/modules/functions.py#L8

**Comment by brunopjacob** [comment]
Fixed in https://github.com/pnnl/neuromancer/pull/191.
