### ISSUE TITLE
Graphviz dependency needs to be installed system-wide

### ISSUE THREAD

**Issue by brunopjacob** [pnnl/neuromancer#186]
I believe the installation of `graphviz` via `pip` alone is not enough to run the `problem.show()`.

For example, running [Part_1_PINN_DiffusionEquation.py](https://github.com/pnnl/neuromancer/blob/master/examples/PDEs/Part_1_PINN_DiffusionEquation.py) in a  system without graphviz installed globally will cause the following issue when reaching [line 337](https://github.com/pnnl/neuromancer/blob/77a606bf3fd57f6ba3b4c6e12cbe7223ab62baad/examples/PDEs/Part_1_PINN_DiffusionEquation.py#L337)

```
>>> dot.render('round-table.gv', view=True)
Traceback (most recent call last):
  File "***/.venv/lib/python3.11/site-packages/graphviz/backend/execute.py", line 78, in run_check
    proc = subprocess.run(cmd, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***/.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "***/.pyenv/versions/3.11.0/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('dot')
```

Suggested fix:
- More invasive: create a script (probably best if it's a python script, as you will need CigWin to run .sh on Windows) to install these kinds of dependencies to the user, automatically
- Less invasive: modify the main README page with directions on how to install graphviz for each system.

**Comment by drgona** [comment]
I would prefer to treat this issue via instructions in README

**Comment by brunopjacob** [comment]
OK, I'll update the documentation on this PR: https://github.com/pnnl/neuromancer/pull/185, along with other fixes.

**Comment by brunopjacob** [comment]
Fixed in https://github.com/pnnl/neuromancer/pull/191.
