### ISSUE TITLE
Error Part_5_nonauto_NSSM

### ISSUE THREAD

**Issue by nsaadati** [pnnl/neuromancer#192]
Hi, I'm encountering an error while trying to implement Example 5 from the system identification module. The error traceback is as follows::

Traceback (most recent call last):
  File "/work/mech-ai-scratch/nsaadati/projects/dt_dpc/DPC_SSM.py", line 121, in <module>
    main(args)
  File "/work/mech-ai-scratch/nsaadati/projects/dt_dpc/DPC_SSM.py", line 99, in main
    best_model = trainer.train()
  File "/home/nsaadati/.conda/envs/neuromancer/lib/python3.10/site-packages/neuromancer/trainer.py", line 246, in train
    output = self.model(t_batch)
  File "/home/nsaadati/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nsaadati/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nsaadati/.conda/envs/neuromancer/lib/python3.10/site-packages/neuromancer/problem.py", line 202, in forward
    return {f'{data["name"]}_{k}': v for k, v in output_dict.items()}
  File "/home/nsaadati/.conda/envs/neuromancer/lib/python3.10/site-packages/neuromancer/problem.py", line 202, in <dictcomp>
    return {f'{data["name"]}_{k}': v for k, v in output_dict.items()}
KeyError: 'name'

It seems the error is related to a missing 'name' key in the data dictionary. Below is the code I'm working with, where I've tried to follow the same logic as the example:

    data_loader = load_data.DPC_DataLoader(args)
    # instantiate neural nets
    nx = data_loader.input_size
    ny = data_loader.output_size
    nu = 1
    train_loader=data_loader.train_loader
    dev_loader=data_loader.dev_loader
    test_data=data_loader.test_dataset

    A = blocks.MLP(nx, nx, bias=True,
                    linear_map=torch.nn.Linear,
                    nonlin=torch.nn.ReLU,
                    hsizes=[40, 40])
    B = blocks.MLP(nu, nx, bias=True,
                    linear_map=torch.nn.Linear,
                    nonlin=torch.nn.ReLU,
                    hsizes=[40, 40])
    # construct NSSM model in Neuromancer
    ssm = SSM(A, B, nx, nu)
    # create symbolic system model in Neuromancer
    model = Node(ssm, ['xn', 'U'], ['xn'], name='NODE')
    dynamics_model = System([model], name='system', nsteps=args.traj_len)
    print(dynamics_model)
    # %% Constraints + losses:
    x = variable("X")
    xhat = variable('xn')[:, :-1, :]

    # trajectory tracking loss
    reference_loss = 5.*(xhat == x)^2
    reference_loss.name = "ref_loss"

    # one step tracking loss
    onestep_loss = 1.*(xhat[:, 1, :] == x[:, 1, :])^2
    onestep_loss.name = "onestep_loss"

    # aggregate list of objective terms and constraints
    objectives = [reference_loss, onestep_loss]
    constraints = []
    # create constrained optimization loss
    loss = PenaltyLoss(objectives, constraints)
    # construct constrained optimization problem
    problem = Problem([dynamics_model], loss)

    problem.show()
    # Save the figure
    fig_path = os.path.join(save_dir, 'problem_figure.png')
    plt.savefig(fig_path)
    print(f'Figure saved to {fig_path}')

    optimizer = torch.optim.Adam(problem.parameters(),
                             lr=0.003)
            
    # trainer
    trainer = Trainer(
        problem,
        train_loader,
        dev_loader,
        test_data,
        optimizer,
        patience=100,
        warmup=100,
        epochs=1000,
        eval_metric="dev_loss",
        train_metric="train_loss",
        dev_metric="dev_loss",
        test_metric="dev_loss",
        )
    best_model = trainer.train()
    problem.load_state_dict(best_model)

**Comment by drgona** [comment]
Hi @nsaadati our [Part 5 example](https://colab.research.google.com/github/pnnl/neuromancer/blob/master/examples/ODEs/Part_5_nonauto_NSSM.ipynb#scrollTo=34498f23) in the system ID set works without issues.

If you have problems with your modified example, these should be discussed via [Discussions](https://github.com/pnnl/neuromancer/discussions) rather than via issues.
