### ISSUE TITLE
I couldn't get both the PDE and variables to be close the prediction 

### ISSUE THREAD

**Issue by AliaNajwaMY** [pnnl/neuromancer#193]
My goal is to solve the inverse problem of the pde u_tt - au_xx - b u_x - c u =0 with u(x,0)=  sin(pix), u(0, t)=u(1,t)=0. I altered the inverse burger's equation accordingly but I couldn't get my loss to get smaller exponentially even after increasing the rate to very high. Other than that, the final predicted a, b and c is also far from what I wanted. Is there any further suggestions that I can implement or look at so that I can get my model to give out better results?
Here is the link to my code

(https://colab.research.google.com/drive/18O-uRYDvKP3wJd-T132OtFA6tniUc1BI?usp=sharing)

**Comment by drgona** [comment]
Dear @AliaNajwaMY, since this is not an issue with the functionality of the library, I suggest you create a new [discussion](https://github.com/pnnl/neuromancer/discussions) to solicit feedback from other users.
