### ISSUE TITLE
Stability Analysis of Actual Cases

### ISSUE THREAD

**Issue by XinyuanLiao** [pnnl/neuromancer#36]
Hello！
I modeled multiple datasets using the decoupled neurodynamic model presented in the paper 'Physics-constrained Deep Learning of Multi-zone Building Thermal Dynamics'. After analyzing the eigenvalues of fx, I found that in my case all models are stable, that is, the spectrum of eigenvalues is less than 1. In this case, do the stability constraints proposed in the paper 'Spectral Analysis and Stability of Deep Neural Dynamics' make sense?

**Comment by drgona** [comment]
Hi @XinyuanLiao, it is likely that the trained neural model will have stable eigenvalues even without hard constraints, especially if the modeled system is stable. However, in general, stability is not guaranteed. The constraints presented in this paper will provide you with stability guarantees in case you need them.
https://ieeexplore.ieee.org/abstract/document/9809789

**Comment by XinyuanLiao** [comment]
Hello, can you provide some examples of modeling instability?

**Comment by drgona** [comment]
@XinyuanLiao yes, for instance, the brusselator system is nonlinear dynamics that has unstable modes
We have an example of parameter estimation for this system. You could modify the code to replace the parametric ODE with neural network to train NeuralODE that will have to learn the dynamics with unstable regions 
https://github.com/pnnl/neuromancer/blob/master/examples/system_identification/brusselator_parameter.py
