### ISSUE TITLE
Redundant or Incorrect Import: 'from neuromancer.component import Component' in modules.solvers

### ISSUE THREAD

**Issue by LucasBoTang** [pnnl/neuromancer#39]
### Describe the bug

Go to [solvers.py line 5](https://github.com/pnnl/neuromancer/blob/7e5e4c163a66367fe35bdc15bb39c4e1259d2afc/src/neuromancer/modules/solvers.py#L5): ``from neuromancer.component import Component``. However, the ``component`` class or module doesn't exist within the current neuromancer package, and it is being used in solvers.py.

### To Reproduce

```python
# import solvers
from neuromancer.modules import solvers
```

**Error Message:**

ModuleNotFoundError: No module named 'neuromancer.component'

**Comment by LucasBoTang** [comment]
There is a similar bug on [gnn.py line 3](https://github.com/pnnl/neuromancer/blob/7e5e4c163a66367fe35bdc15bb39c4e1259d2afc/src/neuromancer/modules/gnn.py#L3) for ``from neuromancer import integrators``. However, ``integrators`` in ``gnn.py`` is used, which seems come from ``neuromancer.dynamics``

**Comment by drgona** [comment]
@LucasBoTang thank you for the pull request fixing this. It has been merged.
