### ISSUE TITLE
Submodule Import

### ISSUE THREAD

**Issue by LucasBoTang** [pnnl/neuromancer#43]
### Describe the bug

Python can't find an attribute or method directly in the module 'neuromancer' and 'neuromancer.modules'. The import statements need to be adjusted in the subpackages.

#### Example 1

```python
import neuromancer as nm
nm.modules.blocks
```

##### **Error Message:**

AttributeError: module 'neuromancer' has no attribute 'modules'

#### Example 2

```python
from neuromancer import modules
modules.blocks.MLP
```

##### **Error Message:**

AttributeError: module 'neuromancer.modules' has no attribute 'blocks'

**Comment by madelynshapiro** [comment]
Resolved by #44 .
