### ISSUE TITLE
pip install options?

### ISSUE THREAD

**Issue by corymosiman12** [pnnl/neuromancer#5]
Is there any way to install neuromancer outside of the conda environment? As a general rule, I tend to not use conda...I was just planning on using venv, but quickly ran into dependencies that aren't hosted on pypi. Thanks

**Comment by aarontuor** [comment]
We currently don't support a pip install but this is on our development pipeline. If you set up an environment with pip install you could share your requirements file from pip freeze in the repo as a pull request and we can edit the readme documentation to include the pip install instructions.
