### ISSUE TITLE
colab import failing

### ISSUE THREAD

**Issue by drgona** [pnnl/neuromancer#60]
@madelynshapiro @aarontuor 

After recent PR merge there is an error in importing neuromancer package in the colab notebooks.

`---------------------------------------------------------------------------
PydanticUserError                         Traceback (most recent call last)
[<ipython-input-1-fefa38f8c0bd>](https://localhost:8080/#) in <cell line: 2>()
      1 import torch
----> 2 from neuromancer.system import Node, System
      3 from neuromancer.modules import blocks
      4 from neuromancer.dataset import DictDataset
      5 from neuromancer.constraint import variable

9 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/class_validators.py](https://localhost:8080/#) in root_validator(pre, skip_on_failure, allow_reuse, *__args)
    226     mode: Literal['before', 'after'] = 'before' if pre is True else 'after'
    227     if pre is False and skip_on_failure is not True:
--> 228         raise PydanticUserError(
    229             'If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`.'
    230             ' Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.',

PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.2/u/root-validator-pre-skip`

**Comment by madelynshapiro** [comment]
This error is a direct result of a bug in MLFlow 2.6.0 which has also been raised in #57.

Proposed solution: we will update the dependency to `mlflow==2.5.0` in our `pyproject.toml` and remove mlflow from `!pip install ...` cells in colab examples.
