### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ChristiaanWewer** [pnnl/neuromancer#65]
Hey,
I might be interested in using this library for my masters thesis. On the documentation webpage you guys refer to a pdf file Documentation.pdf, but it is not there. Is this a mistake, or are its contents merged into the webpages already?
Thanks in advance,
Christiaan

**Comment by drgona** [comment]
Hi @ChristiaanWewer, thank you for your interest in our work! We deprecated the pdf documentation. 
The .rst files generating the online documentation need to be updated to reflect this change. 
For now, the webpage and readme files serve as our documentation for the library.
For more academic documentation of the algorithms, you can also see the papers.
https://github.com/pnnl/neuromancer#publications
