### ISSUE TITLE
Any plans to enable pip or Docker install?

### ISSUE THREAD

**Issue by ogencoglu** [pnnl/neuromancer#7]
Installation with pip or Docker would be really helpful.

**Comment by drgona** [comment]
Hi @ogencoglu, thanks for the request. 
pip or conda install is on our development timeline within a couple of months. Please stay tuned for the updates.
Thanks for the suggestions about the docker, we might include this option as well.

**Comment by clegaard** [comment]
I am currently taking a look at this on a forked version of the repo.
Personally, I think it is worthwhile to support both Pip and Conda.

I have been doing some research and I think we should replace the `setup.py` with a `pyproject.toml` file. More and more build system including Setuptools are transitioning to this.
To support Conda, I think you would need to create a `meta.yml` specifying the dependencies.

I created a fork of `neuromancer`, `psl` and `slim` converting the `setup.py` to a `pyproject.toml` file.
The forked version is passing the testcases on windows, linux and macos:
![image](https://user-images.githubusercontent.com/18687499/220692852-efc94056-98ca-4515-b80b-692c8e8a7249.png)

I'll gladly spend a bit more time to fix up the last things and add test cases for Conda as well :)

**Comment by aarontuor** [comment]
One thing that will simplify the installation process is moving psl and slim in to core neuromancer. This is on the plan for a 1.4 release.

**Comment by aarontuor** [comment]
We now have pip install via current python packaging practices using a .toml file. See instructions in the main readme for pip install.
