### ISSUE TITLE
Small cleanup for pyproject.toml

### ISSUE THREAD

**Issue by Raahul-Singh** [pnnl/neuromancer#71]
In pyproject.toml, scipy is mentioned twice under dependencies:https://github.com/pnnl/neuromancer/blob/3409a46abd6b5f3ef7f0ffbca059df842a8951c8/pyproject.toml#L47 and https://github.com/pnnl/neuromancer/blob/3409a46abd6b5f3ef7f0ffbca059df842a8951c8/pyproject.toml#L52

Should we also create a MANIFEST.in file to explicitly include or exclude non-Python data files. 
We've set https://github.com/pnnl/neuromancer/blob/3409a46abd6b5f3ef7f0ffbca059df842a8951c8/pyproject.toml#L66
which should take care of this, but having a MANIFEST.in would be more declarative.

**Comment by Raahul-Singh** [comment]
Should I go forward with creating a pull request for this? (Is it standard practice in this org to wait for the issue to be assigned before starting working on it?)

**Comment by madelynshapiro** [comment]
@Raahul-Singh Thanks for raising this issue! Please feel free to create a PR for any minor fixes or enhancements such as this one. NeuroMANCER is a relatively new library, so we are currently working on establishing official standard practices for contribution - suggestions and feedback are welcome.
