### ISSUE TITLE
Operational Request: Create an IRC for Neuromancer.

### ISSUE THREAD

**Issue by Raahul-Singh** [pnnl/neuromancer#72]
Can we create a slack workspace or discord server for this project? 
It would be really useful for facilitating collaboration!

**Comment by madelynshapiro** [comment]
We are excited about building a more interactive open-source user community, so thank you for your interest and suggestions @Raahul-Singh ! 

NeuroMANCER has been primarily developed by our core dev team at the Pacific Northwest National Laboratory (PNNL). As a U.S. Dept. of Energy national lab, we are subject to some additional obligations and internal approval procedures for our open-source releases.

Streamlining collaboration with external contributors is a priority for the maintainer team (lead by @drgona and myself), so we are happy to consider this suggestion. We appreciate your patience while we consider our options and obtain any necessary approvals :)

**Comment by Raahul-Singh** [comment]
Thanks @madelynshapiro! 😄 
I'm excited about the future of this project 🚀

**Comment by drgona** [comment]
Hi @Raahul-Singh 
We are setting up [discussions](https://github.com/pnnl/neuromancer/discussions) to facilitate collaboration with our community. 
Here are the recommendations for community development: 
https://github.com/pnnl/neuromancer#community-development
