### ISSUE TITLE
M1 macbook - cannot create conda environment

### ISSUE THREAD

**Issue by corymosiman12** [pnnl/neuromancer#8]
# Summary

Unable to create conda environment:
```raw
(base)
como@Corys-MacBook-Pro-2 [08:59:30] [~/repos/neuromancer] [master]
-> % conda env create -f env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libgd==2.3.3=h695aa2c_1
  - protobuf==3.20.1=py310hd8f1fbe_0
  - graphite2==1.3.14=h295c915_1
  - cvxpy==1.2.1=py310hff52083_0
  - ...lists all packages...
```

# Solution Attempts

- I'm no pro, but it seems strange to me that a prefix exists in the `env.yml` file: `prefix: /home/tuor369/anaconda3/envs/neuromancer`, although, even removing that line from the yml file and running: `conda env create -f env.yml --prefix .envs/` didn't work.
- Update conda
- It may have to do with cross-platform package version resolution, see here: https://stackoverflow.com/a/58160918 and the link to the github issue

# Details
- macOS Ventura 13.1
- Apple M1 Pro
- conda info

```raw
     active environment : base
    active env location : /Applications/miniconda3
            shell level : 1
       user config file : /Users/como/.condarc
 populated config files : /Users/como/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.1=0
                          __unix=0=0
       base environment : /Applications/miniconda3  (writable)
      conda av data dir : /Applications/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Applications/miniconda3/pkgs
                          /Users/como/.conda/pkgs
       envs directories : /Applications/miniconda3/envs
                          /Users/como/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.10.8 Darwin/22.2.0 OSX/13.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by drgona** [comment]
Hi Cory, yeah, the yml files might have some issues. Did you try to install the env manually?
see the instructions below
https://github.com/pnnl/neuromancer#other-operating-system

**Comment by corymosiman12** [comment]
Hey Jan - it's unable to install `cudatoolkit`. Looks like recent versions of cudatoolkit are no longer supporting macOS, and that they never had support for mac M1: https://www.mathworks.com/matlabcentral/answers/1744115-cuda-for-m1-macbook-pro

...sad

That said - is cudatoolkit a requirement, or a nice to have? I'm assuming significant performance degradation without it, even if it was possible?

**Comment by corymosiman12** [comment]
I have some r-pis with ubuntu 20.04 that I'll look to attempt this on

**Comment by drgona** [comment]
Hi Cory, cudatoolkit is optional in case you have access to GPUs.

**Comment by corymosiman12** [comment]
Ok, can confirm. Following the instructions for other operating system, I was able to get up and running. A few notes:
1. `conda install pytorch-scatter -c pyg` - This also didn't come through for me. It seems like, maybe based on [this comment](https://github.com/rusty1s/pytorch_scatter/issues/241#issuecomment-1336116049), this is no longer a separate dependency ?
2. I was able to `conda install casadi` instead of `pip install casadi` (didn't try pip, just tried conda first and it seems to have worked)

Confirm that running the himmelblau and double integrator examples ran through to completion for me with this setup.

My output with running `conda env export --from-history --no-builds > foo.yml`:

```yml
name: neuromancer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - pytorch
  - numpy
  - mlflow
  - numba
  - dill
  - pyts
  - scikit-learn
  - scipy
  - networkx
  - pandas
  - pydot=1.4.2
  - matplotlib
  - plum-dispatch
  - hypothesis
  - pytest
  - tqdm
  - sphinx
  - sphinx_rtd_theme
  - cvxopt
  - seaborn
  - cvxpy
  - casadi
prefix: /Applications/miniconda3/envs/neuromancer
```

**Comment by drgona** [comment]
Thank you so much, Cory. This can be very helpful for other Mac users.
